Made it channel wise
qwerty-mods/invisible-typing pull request #2
Opened 2023-08-22 02:10 UTC by Tharki-God

made the toggle channel wise and the tooltip have info accordingly.

also added an option to make it global instead of channel wise

2023-08-22 02:11 UTC, Tharki-God commented
done https://github.com/qwerty-mods/invisible-typing/issues/1

2023-08-23 14:09 UTC, 12944qwerty requested changes

2023-08-23 14:09 UTC, 12944qwerty commented on src/Settings.tsx
> +      </SwitchItem>
Add a short note describing what it's going to do

2023-08-23 14:09 UTC, 12944qwerty commented on src/index.ts
> +      if (channelWise ? channels[channelId] ?? global : global) {
don't use the global keyword. Use `_global` or something or a different var name.

2023-08-25 13:43 UTC, 12944qwerty approved these changes

2023-08-25 13:43 UTC, merged